# Site settings
title: Dan Keder
header-img: img/bg2.png
email: dan.keder@gmail.com
# python: print ''.join(map(lambda x: '&#%s;'%ord(x), 'me@example.com'))
antispam_email: "&#100;&#97;&#110;&#46;&#107;&#101;&#100;&#101;&#114;&#64;&#103;&#109;&#97;&#105;&#108;&#46;&#99;&#111;&#109;"
description: "Dan Keder's blog"
baseurl: ""
url: "http://keder.me"
twitter_username: xdaneus
github_username:  dankeder
googleplus_username: DanKeder
linkedin_username: keder
disqus_shortname: dankeder
google_analytics_tracking_id: UA-47631149-1

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Dependencies
gems:
  - jekyll-sitemap
