# Site settings
title: Dan Keder
header-img: img/home-bg.jpg
email: dan.keder@gmail.com
description: "Dan Keder's blog"
baseurl: ""
url: "http://keder.me"
twitter_username: xdaneus
github_username:  dankeder
googleplus_username: DanKeder
linkedin_username: keder
disqus_shortname: dankeder
google_analytics_tracking_id: UA-47631149-1

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
